[versions]
minecraft = "1.20.4-R0.1-SNAPSHOT"
minecraftserver = "1.20.4"
googlejavaformat = "1.17.0"
cloud = "2.0.0-beta.4"
[plugins]
userdev = { id = "io.papermc.paperweight.userdev", version = "1.5.12" }
runpaper = { id = "xyz.jpenilla.run-paper", version = "2.2.3" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
lombok = { id = "io.freefair.lombok", version = "8.6" }
paperyml = { id = "net.minecrell.plugin-yml.paper", version = "0.6.0" }
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
[libraries]
annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }
commandframework = { module = "cloud.commandframework:cloud-paper", version = "1.8.4" }
cloud-paper = { module = "org.incendo:cloud-paper", version.ref = "cloud" }
cloud-annotations = { module = "org.incendo:cloud-annotations", version.ref = "cloud" }
cloud-minecraft-extras = { module = "org.incendo:cloud-minecraft-extras", version.ref = "cloud" }
configlib = { module = "de.exlll:configlib-yaml", version = "4.5.0" }
guice = { module = "com.google.inject:guice", version = "7.0.0" }
classgraph = { module = "io.github.classgraph:classgraph", version = "4.8.170" }
paper = { module = "io.papermc.paper:paper-api", version.ref = "minecraft" }
invui = { module = "xyz.xenondevs.invui:invui", version = "1.27" }

[bundles]
cloud = ["cloud-paper", "cloud-annotations", "cloud-minecraft-extras"]